name: PRFlow Login API

on:
  pull_request:
    branches:
      - main
    paths:
      - Source/Services/Tailwind.Traders.Login.Api/**

env:
  # azure
  resourceGroup: twt2021jd
  nameSpace: twt

  # helmchart
  tailwindChartValuesScript: Deploy/powershell/Generate-Config.ps1
  tailwindChartValues: values.yaml
  tailwindCharts: Deploy/helm

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v2

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Create Helm gvalues file"
        run: |
          az extension add --name application-insights
          pwsh $tailwindChartValuesScript -resourceGroup $resourceGroup -outputFile $GITHUB_WORKSPACE/$tailwindChartValues

      - name: "Set PR Environment"
        run: |
          # set for this step
          AKS_CLUSTER=$(az aks list --resource-group $resourceGroup --query [0].name -o tsv)

          echo "AKS_CLUSTER=$(az aks list --resource-group $resourceGroup --query [0].name -o tsv)" >> $GITHUB_ENV

          echo "INGRESS=$(az aks show -n $AKS_CLUSTER -g $resourceGroup --query addonProfiles.httpApplicationRouting.config.HTTPApplicationRoutingZoneName -o tsv)" >> $GITHUB_ENV
          
          echo "Retrieving Container Registry info..."
          acrName=$(az acr list -g $resourceGroup -o tsv --query [0].name)
          CONTAINER_REGISTRY=$(az acr list -g $resourceGroup -o tsv --query [0].loginServer)
          REGISTRY_USERNAME=$(az acr credential show -n $acrName --query username -o tsv)
          REGISTRY_PASSWORD=$(az acr credential show -n $acrName -o tsv --query passwords[0].value)

          echo "CONTAINER_REGISTRY=$(az acr list -g $resourceGroup -o tsv --query [0].loginServer)" >> $GITHUB_ENV
          echo "REGISTRY_USERNAME=$(az acr credential show -n $acrName --query username -o tsv)" >> $GITHUB_ENV
          echo "REGISTRY_PASSWORD=$(az acr credential show -n $acrName -o tsv --query passwords[0].value)" >> $GITHUB_ENV

          # echo "::add-mask::$REGISTRY_USERNAME"
          # echo "::add-mask::$REGISTRY_PASSWORD"

      - name: "Create Registry Secret"
        uses: jldeen/actions-set-secret@releases/v1
        with:
          name: CONTAINER_REGISTRY
          value: ${{ env.CONTAINER_REGISTRY }}
          owner: jldeen
          repository: TailwindTraders-Backend
          token: ${{ secrets.REPO_TOKEN }}   

      # docker login
      - name: "Create Registry User Secret"
        uses: jldeen/actions-set-secret@releases/v1
        with:
          name: REGISTRY_USERNAME
          value: ${{ env.REGISTRY_USERNAME }}
          owner: jldeen
          repository: TailwindTraders-Backend
          token: ${{ secrets.REPO_TOKEN }}

      - name: "Create Registry Password Secret"
        uses: jldeen/actions-set-secret@releases/v1
        with:
          name: REGISTRY_PASSWORD
          value: ${{ env.REGISTRY_PASSWORD }}
          owner: jldeen
          repository: TailwindTraders-Backend
          token: ${{ secrets.REPO_TOKEN }}      

      - name: "docker login"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: docker build / push
        run: |
          docker build -f Source/Services/Tailwind.Traders.Login.Api/Dockerfile Source -t  $CONTAINER_REGISTRY/login.api:$GITHUB_SHA
          docker push $CONTAINER_REGISTRY/login.api:$GITHUB_SHA

      - uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ${{ env.AKS_CLUSTER }}
          resource-group: ${{ env.resourceGroup }}

      - name: Create valid branch name
        id: generate-valid-branch-name
        run: |
          branch=${GITHUB_HEAD_REF::63}        
          branch=$(echo ${branch//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
          echo ::set-output name=result::$branch

      - name: Helm Install PR
        run: |
          helm upgrade --install --namespace  ${{ env.nameSpace }} ${{steps.generate-valid-branch-name.outputs.result}} \
          -f $tailwindChartValues \
          --set ingress.hosts={$INGRESS} \
          --set image.repository=$CONTAINER_REGISTRY/login.api \
          --set image.tag=$GITHUB_SHA $tailwindCharts/login-api \
          --set B2C.clientID=none \
          --set B2C.identityMetadata=none \
          --set B2C.issuer=none \
          --set B2C.policyName=none \
          --set B2C.tenantID=none

      - name: Add routing labels
        run: |
          kubectl label pods --selector="app=tailwindtraders-login,release=${{steps.generate-valid-branch-name.outputs.result}}" routing.visualstudio.io/route-from=${{steps.generate-valid-branch-name.outputs.result}}-tailwindtraders-login -n ${{ env.nameSpace }} --overwrite=true
          kubectl annotate pods --selector="app=tailwindtraders-login,release=${{steps.generate-valid-branch-name.outputs.result}}" routing.visualstudio.io/route-on-header=kubernetes-route-as=${{steps.generate-valid-branch-name.outputs.result}} -n ${{ env.nameSpace }} --overwrite=true
          
      - uses: jldeen/dev-spaces/actions/add-review-url@Releases/v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          host: "${{ env.INGRESS }}"
          branch-name: ${{steps.generate-valid-branch-name.outputs.result}}
          protocol: "http"